# Generated by Django 4.2.4 on 2023-08-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='Марка')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('rudely_location', models.CharField(max_length=100, verbose_name='Расположения руля')),
                ('engine_volume', models.PositiveSmallIntegerField(verbose_name='Объем двигателя')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
